# Generated by Django 5.2.7 on 2025-11-04 22:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pessoa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "criado",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado"),
                ),
                (
                    "modificado",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado"),
                ),
                (
                    "descricao",
                    models.CharField(
                        max_length=255, unique=True, verbose_name="Descrição"
                    ),
                ),
                (
                    "tipo_pessoa",
                    models.CharField(
                        choices=[("PF", "Pessoa Física"), ("PJ", "Pessoa Jurídica")],
                        default="PF",
                        max_length=2,
                        verbose_name="Tipo de Pessoa",
                    ),
                ),
                (
                    "eh_cliente",
                    models.BooleanField(default=False, verbose_name="É Cliente"),
                ),
                (
                    "eh_fornecedor",
                    models.BooleanField(default=False, verbose_name="É Fornecedor"),
                ),
                (
                    "eh_transportadora",
                    models.BooleanField(default=False, verbose_name="É Transportadora"),
                ),
                ("ativo", models.BooleanField(default=True, verbose_name="Ativo")),
                (
                    "observacoes",
                    models.TextField(blank=True, verbose_name="Observações"),
                ),
                (
                    "colaborador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pessoas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Colaborador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pessoa",
                "verbose_name_plural": "Pessoas",
                "ordering": ["descricao"],
            },
        ),
    ]
