# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('fiscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cfop_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.naturezaoperacao'),
        ),
        migrations.AddField(
            model_name='produto',
            name='grupo_fiscal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fiscal.grupofiscal'),
        ),
        migrations.AddField(
            model_name='produto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.marca'),
        ),
        migrations.AddField(
            model_name='site',
            name='pessoa_site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='site_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sit_padrao', to='cadastro.site'),
        ),
        migrations.AddField(
            model_name='telefone',
            name='pessoa_tel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefone', to='cadastro.pessoa'),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='telefone_padrao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tel_padrao', to='cadastro.telefone'),
        ),
        migrations.AddField(
            model_name='produto',
            name='unidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastro.unidade'),
        ),
        migrations.AddField(
            model_name='minhaempresa',
            name='m_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='minha_empresa', to='cadastro.empresa'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='transportadora_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='veiculo', to='cadastro.transportadora'),
        ),
    ]
