# Generated by Django 3.1.14 on 2025-05-30 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_auto_20170820_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lancamento',
            options={'verbose_name': 'Lançamento'},
        ),
        migrations.AlterModelOptions(
            name='movimentocaixa',
            options={'permissions': (('acesso_fluxodecaixa', 'Pode acessar o Fluxo de Caixa'),), 'verbose_name': 'Movimento de Caixa'},
        ),
        migrations.AlterModelOptions(
            name='planocontasgrupo',
            options={'verbose_name': 'Grupo do Plano de Contas'},
        ),
    ]
