# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mod_frete', models.CharField(choices=[('0', 'Por conta do emitente'), ('1', 'Por conta do destinatário/remetente'), ('2', 'Por conta de terceiros'), ('9', 'Sem frete')], default='9', max_length=1)),
                ('movimentar_estoque', models.BooleanField(default=True)),
                ('data_emissao', models.DateField(blank=True, null=True)),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tipo_desconto', models.CharField(choices=[('0', 'Valor'), ('1', 'Percentual')], default='0', max_length=1)),
                ('desconto', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('despesas', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('frete', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('seguro', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_icms', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_ipi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.CharField(blank=True, max_length=1055, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItensCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('tipo_desconto', models.CharField(blank=True, choices=[('0', 'Valor'), ('1', 'Percentual')], max_length=1, null=True)),
                ('desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inf_ad_prod', models.CharField(blank=True, max_length=500, null=True)),
                ('vicms', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('vipi', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('p_icms', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('p_ipi', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('icms_incluido_preco', models.BooleanField(default=False)),
                ('ipi_incluido_preco', models.BooleanField(default=False)),
                ('incluir_bc_icms', models.BooleanField(default=False)),
                ('auto_calcular_impostos', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indice_parcela', models.IntegerField()),
                ('vencimento', models.DateField()),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
        ),
        migrations.CreateModel(
            name='OrcamentoCompra',
            fields=[
                ('compra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compras.compra')),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Aberto'), ('1', 'Baixado'), ('2', 'Cancelado')], default='0', max_length=1)),
            ],
            options={
                'verbose_name': 'Orçamento de Compra',
            },
            bases=('compras.compra',),
        ),
        migrations.CreateModel(
            name='PedidoCompra',
            fields=[
                ('compra_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='compras.compra')),
                ('data_entrega', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('0', 'Aberto'), ('1', 'Realizado'), ('2', 'Cancelado'), ('3', 'Importado por XML'), ('4', 'Recebido')], default='0', max_length=1)),
            ],
            options={
                'verbose_name': 'Pedido de Compra',
                'permissions': (('faturar_pedidocompra', 'Pode faturar Pedidos de Compra'),),
            },
            bases=('compras.compra',),
        ),
    ]
