# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('compras', '0001_initial'),
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cond_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_pagamento', to='vendas.condicaopagamento'),
        ),
        migrations.AddField(
            model_name='compra',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compra_fornecedor', to='cadastro.fornecedor'),
        ),
        migrations.AddField(
            model_name='compra',
            name='local_dest',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='compra_local_estoque', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='itenscompra',
            name='compra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_compra', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='itenscompra',
            name='produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='compra_produto', to='cadastro.produto'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='compra_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcela_pagamento', to='compras.compra'),
        ),
        migrations.AddField(
            model_name='pedidocompra',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_pedido', to='compras.orcamentocompra'),
        ),
    ]
