# Generated by Django 3.1.14 on 2025-05-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0004_auto_20250530_0127"),
        ("vendas", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="condicaopagamento",
            options={"verbose_name": "Condição de Pagamento"},
        ),
        migrations.AlterModelOptions(
            name="orcamentovenda",
            options={"verbose_name": "Orçamento de Venda"},
        ),
        migrations.AlterModelOptions(
            name="pedidovenda",
            options={
                "permissions": (("faturar_pedidovenda", "Pode faturar Pedidos de Venda"),),
                "verbose_name": "Pedido de Venda",
            },
        ),
        migrations.AlterField(
            model_name="venda",
            name="local_orig",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="venda_local_estoque",
                to="estoque.localestoque",
            ),
        ),
    ]
