# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimentoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_movimento', models.DateField(blank=True, null=True)),
                ('quantidade_itens', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('observacoes', models.CharField(blank=True, max_length=1055, null=True)),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'permissions': (('consultar_estoque', 'Pode consultar estoque'),),
            },
        ),
        migrations.CreateModel(
            name='LocalEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=1055)),
            ],
            options={
                'verbose_name': 'Local de Estoque',
            },
        ),
        migrations.CreateModel(
            name='TransferenciaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.movimentoestoque')),
            ],
            bases=('estoque.movimentoestoque',),
        ),
        migrations.CreateModel(
            name='ItensMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('valor_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('movimento_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_movimento', to='estoque.movimentoestoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moviment_estoque_produto', to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoEstocado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=13, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_produto_estocado', to='estoque.localestoque')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produto_estocado', to='cadastro.produto')),
            ],
        ),
        migrations.AddField(
            model_name='localestoque',
            name='produtos_estoque',
            field=models.ManyToManyField(through='estoque.ProdutoEstocado', to='cadastro.produto'),
        ),
        migrations.CreateModel(
            name='EntradaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.movimentoestoque')),
                ('tipo_movimento', models.CharField(choices=[('0', 'Ajuste'), ('1', 'Entrada por pedido de compra'), ('2', 'Entrada por importação de nota fiscal de fornecedor'), ('3', 'Ajuste inicial')], default='0', max_length=1)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_estoque_fornecedor', to='cadastro.fornecedor')),
                ('local_dest', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='entrada_estoque_local', to='estoque.localestoque')),
                ('pedido_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrada_estoque_pedido', to='compras.pedidocompra')),
            ],
            bases=('estoque.movimentoestoque',),
        ),
        migrations.CreateModel(
            name='SaidaEstoque',
            fields=[
                ('movimentoestoque_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='estoque.movimentoestoque')),
                ('tipo_movimento', models.CharField(choices=[('0', 'Ajuste'), ('1', 'Saída por pedido de venda'), ('2', 'Saída por importação de nota fiscal')], default='0', max_length=1)),
                ('local_orig', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='saida_estoque_local', to='estoque.localestoque')),
            ],
            bases=('estoque.movimentoestoque',),
        ),
    ]
