# Generated by Django 5.2.7 on 2025-11-04 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estoque', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidaestoque',
            name='pedido_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saida_estoque', to='vendas.pedidovenda'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_estoque_dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transf_estoque_dest', to='estoque.localestoque'),
        ),
        migrations.AddField(
            model_name='transferenciaestoque',
            name='local_estoque_orig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transf_estoque_orig', to='estoque.localestoque'),
        ),
    ]
